Repository majd/ipatool, pull requests merged in 2022-03, with the labels that each got.

#48 Update readme
  README.md
  demo.gif
Labels: documentation

#55 Implement `auth` command
  .github/workflows/integration-tests.yml
  .swiftpm/xcode/xcshareddata/xcschemes/IPATool-Package.xcscheme
  Package.resolved
  Package.swift
  README.md
  Sources/CLI/Commands/Auth.swift
  Sources/CLI/Commands/Download.swift
  Sources/CLI/Commands/IPATool.swift
  Sources/CLI/Models/Account.swift
  Sources/Persistence/KeychainStore.swift
Labels: enhancement

#56 Implement `purchase` command
  .github/workflows/integration-tests.yml
  README.md
  Sources/CLI/Commands/Download.swift
  Sources/CLI/Commands/IPATool.swift
  Sources/CLI/Commands/Purchase.swift
  Sources/CLI/Commands/Search.swift
  Sources/Networking/HTTPResponse.swift
  Sources/StoreAPI/Common/Storefront.swift
  Sources/StoreAPI/Store/StoreClient.swift
  Sources/StoreAPI/Store/StoreEndpoint.swift
  Sources/StoreAPI/Store/StoreRequest.swift
  Sources/StoreAPI/Store/StoreResponse.swift
  Sources/StoreAPI/iTunes/iTunesClient.swift
  Sources/StoreAPI/iTunes/iTunesRequest.swift
Labels: enhancement

#57 Implement `--purchase` flag in `download` command
  README.md
  Sources/CLI/Commands/Download.swift
  Sources/CLI/Commands/Purchase.swift
Labels: enhancement

#58 Add price checks for purchase flow
  Sources/CLI/Commands/Download.swift
  Sources/CLI/Commands/Purchase.swift
  Sources/StoreAPI/Store/StoreResponse.swift
  Sources/StoreAPI/iTunes/iTunesResponse.swift
Labels: enhancement

#59 Fix typos
  Sources/CLI/Commands/Download.swift
  Sources/CLI/Commands/Purchase.swift
Labels: bug
